<a href="https://colab.research.google.com/github/Shambhavi410/BCS-Winter-Project-STACK-O-MATIC/blob/main/BCS_Assignment_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part 1: Data Exploration with Pandas**

### **Load the Dataset**

In [1]:
#Loading the dataset from the CSV file into a Pandas DataFrame
import pandas as pd
import numpy as np
data=pd.read_csv('/content/sample_data/california_housing_train.csv')
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [2]:
#first 5 rows
data.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [3]:
#last 10 rows
data.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

### **Data Summary**

In [4]:
#statistical summary
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [5]:
#unique values in the total_bedrooms column
print(data['total_bedrooms'].unique())

[1283. 1901.  174. ... 1637. 1308.  936.]


In [6]:
#number of distinct values in the total_bedrooms column
data['total_bedrooms'].value_counts()

total_bedrooms
280.0     48
309.0     44
331.0     43
394.0     43
345.0     43
          ..
2405.0     1
1797.0     1
1024.0     1
1494.0     1
936.0      1
Name: count, Length: 1848, dtype: int64

### **Data Transformation**

In [7]:
#Adding new column total_bedrooms_per_total_rooms
data['total_bedrooms_per_total_rooms']=data['total_bedrooms']/data['total_rooms']
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  \
0          1015.0       472.0         1.4936             66900.0   
1          1129.0       463.0         1.8200             80100.0   
2           333.0       117.0         1.6509             85700.0   
3           515.0       226.0         3.1917             73400.0   
4           624.0       262.0         1.9250             65500.0   
...           ...         ...            ...                 ...   
16995       907.0       369.0         2.3571            111400.0   
16996      1194.0       465.0         2.5179             79000.0   
16997      1244.0       456.0         3.0313            103600.0   
16998      1298.0       478.0         1.9797             85800.0   
16999       806.0       270.0         3.0147             94600.0   

       total_bedrooms_per_total_rooms  
0                            0.228617  
1                            0.248497  
2                            0.241667  
3                            0.224517  
4                            0.224209  
...                               ...  
16995                        0.177718  
16996                        0.224777  
16997                        0.198356  
16998                        0.206587  
16999                        0.164835  

[17000 rows x 10 columns]

In [8]:
#Mean and standard deviation of column total_bedrooms_per_total_rooms
print("Mean: ",data['total_bedrooms_per_total_rooms'].mean())
print("Standard Deviation: ",data['total_bedrooms_per_total_rooms'].std())

Mean:  0.21275998821034803
Standard Deviation:  0.057823008903161756


### **Data Filtering**

In [9]:
#Filtered dataset having rows in which median_income is greater than 5
data.loc[(data['median_income']>5)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [10]:
#Creating and printing the subset of the data where total_rooms>10,000 and median_house_value<$150,000
subset=data.loc[(data['total_rooms']>10000) & (data['median_house_value']<150000)]
subset

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

### **Export Modified Data**

In [11]:
#Exporting the modified DataFrame to a new CSV file
data.to_csv('/content/sample_data/california_housing_train_new.csv',index=False)

# **Part 2: Numerical Analysis with NumPy**

### **Array Creation and Indexing**

In [12]:
#Create a 1D NumPy array of integers from 1 to 20
a=np.arange(1,21)
print("Array of integers from 1 to 20:\n",a)

Array of integers from 1 to 20:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
#Extract the even numbers from this array using slicing
print("Even numbers of the array:\n",a[1::2])

Even numbers of the array:
 [ 2  4  6  8 10 12 14 16 18 20]


In [14]:
#2D array with 5 rows and 4 columns, filled with random integers between 10 and 100
b=np.random.randint(11,100,size=(5,4))
print("5x4 array filled with random integers between 10 and 100:\n",b)

5x4 array filled with random integers between 10 and 100:
 [[31 73 38 42]
 [68 12 58 32]
 [26 14 95 25]
 [53 69 95 25]
 [97 40 19 22]]


In [15]:
#Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns)
extract=b[:3,:2]
print("3x2 subarray from the 2D array:\n",extract)

3x2 subarray from the 2D array:
 [[31 73]
 [68 12]
 [26 14]]


### **Array Manipulation**

In [16]:
#Reshape the 1D array of integers into a 4x5 2D array
a=a.reshape((4,5))
print("Reshaped array:\n",a)

Reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
#Flatten the 2D array back to a 1D array and print it
a=a.reshape((20,))
print("Flattened array:\n",a)

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [18]:
#Matrix multiplication between two 2D arrays (second 2D array randomly is generated randomly)
c=np.random.rand(4,3)
print("Second random 2D matrix is:\n",c)
r=np.matmul(b,c)
print("Matrix multiplication of the two 2D matrices:\n",r)

Second random 2D matrix is:
 [[0.3853053  0.8531738  0.18889147]
 [0.38915033 0.51386015 0.43570508]
 [0.63395391 0.10160945 0.8546995 ]
 [0.99138694 0.37932262 0.81961341]]
Matrix multiplication of the two 2D matrices:
 [[106.0809381   83.75288825 104.56445118]
 [ 99.36427289  82.21381282  93.87328128]
 [100.47633715  48.51252477 112.69783756]
 [132.2828482   99.81052564 141.76168682]
 [ 86.79626383 113.58794233  70.0214614 ]]


### **Boolean and Fancy Indexing**

In [19]:
#A NumPy array of 50 random integers between 0 and 100
d=np.random.randint(1,100,size=(50,))
print("Array of 50 random integers between 0 and 100\n",d)

Array of 50 random integers between 0 and 100
 [11 77 54  2 94 20 47 12 68 23 39 57  7 92 72 50 68 27 37 62  1 30  8 17
 33 33 39  2 94 60 98 90 95 45 98 18 43 10 70 87 20 71  4 68 54 85 35 21
 58 48]


In [20]:
#Used Boolean indexing to extract all values greater than 50 from the array
extract2=d[d>50]
print("Values greater than 50:\n",extract2)

Values greater than 50:
 [77 54 94 68 57 92 72 68 62 94 60 98 90 95 98 70 87 71 68 54 85 58]


In [21]:
#Use fancy indexing to extract elements from the array at specific indices
print("Elements at specific indices (example indices- 3,6,18,32):\n",d[[3,6,18,32]])

Elements at specific indices (example indices- 3,6,18,32):
 [ 2 47 37 95]


### **Statistical Operations**

In [22]:
#For the 2D array created earlier, calculate the mean, max, and sum along each column
print("Mean along each column:\n",np.mean(b,axis=0))
print("Max along each column:\n",np.max(b,axis=0))
print("Sum along each column:\n",np.sum(b,axis=0))

Mean along each column:
 [55.  41.6 61.  29.2]
Max along each column:
 [97 73 95 42]
Sum along each column:
 [275 208 305 146]


In [23]:
#Create a mask to select elements that are greater than the mean value for each column and apply the mask to filter the array
mask=b>np.mean(b,axis=0)
print("Mask:\n",mask)
print("Filtered array\n",b[mask])

Mask:
 [[False  True False  True]
 [ True False False  True]
 [False False  True False]
 [False  True  True False]
 [ True False False False]]
Filtered array
 [73 42 68 32 95 69 95 97]


# **Part 3: Problem Solving with Python Basics**

### **Loops and Conditional Statements**

In [24]:
#Fibonacci sequence up to 100 using a loop
e=0
f=1
L=[0,1]
while e<=100:
    g=f
    f=e+f
    if f<=100:
        L.append(f)
    else:
        break
    e=g
print("Fibonacci sequence up to 100:\n",L)

Fibonacci sequence up to 100:
 [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [25]:
#Loop through the numbers from 1 to 50 and print: "Fizz" for multiples of 3; "Buzz" for multiples of 5; "FizzBuzz" for multiples of both 3 and 5
for i in range(1,51):
    if (i%3==0 and i%5!=0):
        print("Fizz")
    elif (i%5==0 and i%3!=0):
        print("Buzz")
    elif (i%3==0 and i%5==0):
        print("FizzBuzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


### **Variable-Length Arguments**

In [26]:
#Write a solution that accepts a list of numbers and returns the median value
x=input("Enter a list of numbers separated by comma: ")
P=[]
for i in x.split(','):
      P.append(int(i))
P.sort()
y=len(P)
if y%2!=0:
    print("Median= ",P[((y+1)//2)-1])
else:
    print("Median= ",(P[(y//2)-1]+P[y//2])/2)

Enter a list of numbers separated by comma: 1,2,3
Median=  2


In [27]:
#Write a solution that accepts a variable number of arguments and returns the average of the numbers
x=input("Enter a list of numbers separated by comma: ")
A=[]
for i in x.split(','):
        A.append(int(i))
print("Average= ",sum(A)/len(A))

Enter a list of numbers separated by comma: 1,2,3
Average=  2.0


### **Error Handling**

In [28]:
#Handle the case where a division by zero occurs and print an appropriate error message.
num=int(input("Numerator: "))
den=int(input("Denominator: "))
if den==0:
    print("Division by 0 is not defined")
else:
    print(num/den)

#OR

try:
    result=num/den
    print(result)
except ZeroDivisionError:
    print("Division by 0 is not defined")

Numerator: 3
Denominator: 0
Division by 0 is not defined
Division by 0 is not defined


# **Part 4: Bonus Challenge (Optional)**

### **Advanced NumPy Manipulation**

In [29]:
#Create a 3D NumPy array with specific dimensions and populate it with random numbers
s=np.random.rand(3,4,5)
print(s)

[[[0.39181624 0.16640909 0.89776899 0.31421552 0.28511285]
  [0.32034669 0.97898268 0.72593361 0.43608447 0.42404579]
  [0.45645705 0.29789812 0.97886394 0.00895756 0.18303398]
  [0.31578655 0.13946244 0.08449966 0.38564532 0.48153608]]

 [[0.236407   0.82039581 0.01241399 0.46255163 0.02856997]
  [0.37372019 0.19916834 0.99750346 0.65809476 0.77130104]
  [0.37878496 0.8158442  0.9394573  0.54058879 0.23563845]
  [0.10184166 0.06098023 0.45708315 0.09456067 0.70164192]]

 [[0.84386303 0.98391165 0.54690019 0.56823401 0.62652252]
  [0.17391967 0.98348134 0.94724797 0.43539918 0.98528588]
  [0.64900616 0.18854082 0.58864597 0.42796773 0.32324851]
  [0.61639821 0.47523999 0.68418472 0.94427595 0.07922736]]]


In [30]:
#Swap two of its axes
#Let the three axes be (0,1,2)
#swapping axes 1 and 2
#The new 3D array with axes 1 and 2 swapped will be the one with the above three matrices transposed
new=np.zeros((3,5,4))
for i in range(3):
  for j in range(5):
    for k in range(4):
      new[i][j][k]=s[i][k][j]
print("Swapped axes 1 and 2 new 3D array:\n",new)

Swapped axes 1 and 2 new 3D array:
 [[[0.39181624 0.32034669 0.45645705 0.31578655]
  [0.16640909 0.97898268 0.29789812 0.13946244]
  [0.89776899 0.72593361 0.97886394 0.08449966]
  [0.31421552 0.43608447 0.00895756 0.38564532]
  [0.28511285 0.42404579 0.18303398 0.48153608]]

 [[0.236407   0.37372019 0.37878496 0.10184166]
  [0.82039581 0.19916834 0.8158442  0.06098023]
  [0.01241399 0.99750346 0.9394573  0.45708315]
  [0.46255163 0.65809476 0.54058879 0.09456067]
  [0.02856997 0.77130104 0.23563845 0.70164192]]

 [[0.84386303 0.17391967 0.64900616 0.61639821]
  [0.98391165 0.98348134 0.18854082 0.47523999]
  [0.54690019 0.94724797 0.58864597 0.68418472]
  [0.56823401 0.43539918 0.42796773 0.94427595]
  [0.62652252 0.98528588 0.32324851 0.07922736]]]


In [31]:
#Swapping axes 0 and 2
new=np.zeros((5,4,3))
for i in range(5):
  for j in range(4):
    for k in range(3):
      new[i][j][k]=s[k][j][i]
print("Swapped axes 0 and 2 new 3D array:\n",new)

Swapped axes 0 and 2 new 3D array:
 [[[0.39181624 0.236407   0.84386303]
  [0.32034669 0.37372019 0.17391967]
  [0.45645705 0.37878496 0.64900616]
  [0.31578655 0.10184166 0.61639821]]

 [[0.16640909 0.82039581 0.98391165]
  [0.97898268 0.19916834 0.98348134]
  [0.29789812 0.8158442  0.18854082]
  [0.13946244 0.06098023 0.47523999]]

 [[0.89776899 0.01241399 0.54690019]
  [0.72593361 0.99750346 0.94724797]
  [0.97886394 0.9394573  0.58864597]
  [0.08449966 0.45708315 0.68418472]]

 [[0.31421552 0.46255163 0.56823401]
  [0.43608447 0.65809476 0.43539918]
  [0.00895756 0.54058879 0.42796773]
  [0.38564532 0.09456067 0.94427595]]

 [[0.28511285 0.02856997 0.62652252]
  [0.42404579 0.77130104 0.98528588]
  [0.18303398 0.23563845 0.32324851]
  [0.48153608 0.70164192 0.07922736]]]


In [32]:
#Swapping axes 0 and 1
new=np.zeros((4,3,5))
for i in range(4):
  for j in range(3):
    for k in range(5):
      new[i][j][k]=s[j][i][k]
print("Swapped axes 0 and 1 new 3D array:\n",new)

Swapped axes 0 and 1 new 3D array:
 [[[0.39181624 0.16640909 0.89776899 0.31421552 0.28511285]
  [0.236407   0.82039581 0.01241399 0.46255163 0.02856997]
  [0.84386303 0.98391165 0.54690019 0.56823401 0.62652252]]

 [[0.32034669 0.97898268 0.72593361 0.43608447 0.42404579]
  [0.37372019 0.19916834 0.99750346 0.65809476 0.77130104]
  [0.17391967 0.98348134 0.94724797 0.43539918 0.98528588]]

 [[0.45645705 0.29789812 0.97886394 0.00895756 0.18303398]
  [0.37878496 0.8158442  0.9394573  0.54058879 0.23563845]
  [0.64900616 0.18854082 0.58864597 0.42796773 0.32324851]]

 [[0.31578655 0.13946244 0.08449966 0.38564532 0.48153608]
  [0.10184166 0.06098023 0.45708315 0.09456067 0.70164192]
  [0.61639821 0.47523999 0.68418472 0.94427595 0.07922736]]]


In [33]:
#Perform an operation to calculate the sum of all the elements along a particular axis
#Let towards x axis there be 5 elements, towards y axis there be 4 elements and towards z axis there be 3 elements

#Sum along axis 0:
print("Sum along axis 0:\n",np.sum(s,axis=0))
#Sum along axis 1:
print("Sum along axis 1:\n",np.sum(s,axis=1))
#Sum along axis 2:
print("Sum along axis 2:\n",np.sum(s,axis=2))

Sum along axis 0:
 [[1.47208627 1.97071655 1.45708317 1.34500117 0.94020535]
 [0.86798656 2.16163236 2.67068504 1.52957841 2.18063272]
 [1.48424816 1.30228314 2.50696721 0.97751408 0.74192094]
 [1.03402643 0.67568266 1.22576752 1.42448195 1.26240536]]
Sum along axis 1:
 [[1.48440653 1.58275233 2.68706619 1.14490287 1.37372871]
 [1.09075381 1.89638858 2.4064579  1.75579586 1.73715139]
 [2.28318707 2.63117379 2.76697885 2.37587688 2.01428427]]
Sum along axis 2:
 [[2.0553227  2.88539324 1.92521065 1.40693004]
 [1.5603384  2.9997878  2.9103137  1.41610765]
 [3.56943141 3.52533405 2.17740918 2.79932622]]


In [34]:
#Generate a random array and use broadcasting to perform an operation that adds a vector to each row of a 2D array
arr=np.random.rand(5,3)
print("Random Array:\n",arr)
vec=np.random.rand(3,)
print("Vector:\n",vec)
res=arr+vec
print("Answer:\n",res)

Random Array:
 [[0.26691231 0.92832733 0.58129858]
 [0.74398713 0.06609906 0.88742027]
 [0.42511606 0.92588776 0.54537401]
 [0.44051606 0.72868565 0.26853224]
 [0.04940338 0.10779912 0.85658594]]
Vector:
 [0.75109402 0.82528317 0.28527713]
Answer:
 [[1.01800632 1.75361051 0.86657572]
 [1.49508114 0.89138223 1.17269741]
 [1.17621007 1.75117093 0.83065115]
 [1.19161008 1.55396882 0.55380937]
 [0.80049739 0.93308229 1.14186308]]
